//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveExams.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosQueJoin
    {
        public int ID { get; set; }
        public int PositionID { get; set; }
        public long QueCatID { get; set; }
        public Nullable<int> NoOfQuestion { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Position Position { get; set; }
        public virtual QuestionCategory QuestionCategory { get; set; }
    }
}
